title: "MLNA Documentation"
description: "A Python package for MultiLingual Network Analysis"
baseurl: "/docs"
url: "https://Goli-SF.github.io"

remote_theme: "pmarsceill/just-the-docs"

markdown: kramdown
highlighter: rouge

just_the_docs:
  search_enabled: true
  show_toc: true
  toc_depth: 2
